spring:
  application:
    name: quiz-generator
  data:
    mongodb:
      url: mongodb://localhost:27017/quistionsdb
server:
  port: 9097
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/